spring:
  application:
    name: DATA-SOURCE

  datasource:
    url: jdbc:h2:mem:dev
  h2:
    console.enabled: true

  rabbitmq:
    address: localhost
    port: 5672
    password: guest
    username: guest

# HTTP
server:
  port: 8082

# Cloud
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# messaging
messaging:
  queue: queue
  exchange: exchange
  routingKey: routing_key

# Swagger
springdoc.swagger-ui.path: "swagger.html"